[package]
name = "gfapi"
description = "This crates provides FFI bindings for Gluster's API"
version = "0.1.0"
authors = ["Chris Holcombe <chris.holcombe@canonical.com>"]
repository = "https://github.com/cholcombe973/Gfapi-sys"
license = "MIT"

[dependencies]
errno = "*"
libc = "*"
